App_banAo/Controllers/ThongKeController.cs
using App_banAo.Models;
using App_data.Models;
using App_data.ViewModels;
using App_data.ViewModels.ThongKe;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;

namespace App_banAo.Controllers
{
    public class ThongKeController : Controller
    {
        private readonly HttpClient _httpClient;
        public ThongKeController()
        {
            _httpClient = new HttpClient();
        }
        #region Thống Kê Sản Phẩm Được Mua nhiều Theo Ngày, Tháng, Năm 
        [HttpGet]

        public async Task<IActionResult> ThongKeSP()
        {
            string apiUrl = $"https://localhost:7016/api/ThongKe/ThongKeMSSanPhamBan";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeMSSanPhamTheoSoLuong>>(apiData);

            return View(ChatLieus);
        }
        [HttpGet]
        public async Task<IActionResult> ThongKeSPTheoThang(DateTime? ngay, DateTime? thang, DateTime? nam)
        {

            string apiUrl = $"https://localhost:7016/api/ThongKe/ThongKeMSSanPhamBan";
            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeMSSanPhamTheoSoLuong>>(apiData);
            var timkiem = ChatLieus.ToList();

            if (ngay.HasValue)
            {
                timkiem = ChatLieus.Where(x => x.Ngay.Date == ngay.Value.Date && x.Ngay.Month == ngay.Value.Month && x.Ngay.Year == ngay.Value.Year).ToList();
            }
            if (thang.HasValue)
            {
                timkiem = ChatLieus.Where(x => x.Ngay.Month == thang.Value.Month && x.Ngay.Year == thang.Value.Year).ToList();
            }
            if (nam.HasValue)
            {
                timkiem = ChatLieus.Where(x => x.Ngay.Year == nam.Value.Year).ToList();
            }

            return View("ThongKeSP", timkiem);
        }
        #endregion
        #region Thông Kê Khách Hàng Mua Nhiêù Theo Ngày, Tháng , Năm
        public int PageSize = 8;
        [HttpGet]

        public async Task<IActionResult> ThongKeKH(int ProductPage = 1)
        {
            string apiUrl = $"https://localhost:7016/api/ThongKe/ThongKeKHTheoSoLuongHoaDon";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeKHMuaNhieu>>(apiData);

            return View(new PhanTrangThongKeKH
            {
                listkhs = ChatLieus
                        .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    ItemsPerPage = PageSize,
                    CurrentPage = ProductPage,
                    TotalItems = ChatLieus.Count()
                }

            }
                );
        }
        [HttpGet]
        public async Task<IActionResult> ThongKeSPKHTheoThang(DateTime ThangStart, DateTime ThangEnd, int ProductPage = 1)
        {

            string apiUrl = $"https://localhost:7016/api/ThongKe/ThongKeKHTheoSoLuongHoaDon";
            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeKHMuaNhieu>>(apiData);
            var timkiem = ChatLieus.ToList();

            timkiem = timkiem.Where(x => x.Ngay.Month >= ThangStart.Month && x.Ngay.Month <= ThangEnd.Month).ToList();

            return View("ThongKeKH", new PhanTrangThongKeKH
            {
                listkhs = timkiem
                         .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    ItemsPerPage = PageSize,
                    CurrentPage = ProductPage,
                    TotalItems = timkiem.Count()
                }

            }
                 );
        }
       
       
        #endregion
        #region Thông Kê Doanh Thu  Theo Ngày, Tháng , Năm
        [HttpGet]
        public async Task<IActionResult> ThongKeDoanhThuTheoNgay()
        {
            string apiUrl = $"https://localhost:7016/api/ThongKe/ThongKeDoanhThuTheoNgay";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeDoanhThu>>(apiData);

            return View(ChatLieus);
        }
        [HttpGet]
        public async Task<IActionResult> LocThongKeDoanhThuTheoNgay(DateTime NgayStart, DateTime NgayEnd)
        {
            string apiUrl = $"https://localhost:7016/api/ThongKe/ThongKeDoanhThuTheoNgay";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeDoanhThu>>(apiData);
            var timkiem = ChatLieus.ToList();

            timkiem = timkiem.Where(x => x.Ngay.Date >= NgayStart.Date && x.Ngay.Date <= NgayEnd.Date).ToList();
            return View("ThongKeDoanhThuTheoNgay", timkiem);
        }
        [HttpGet]
        public async Task<IActionResult> ThongKeDoanhThuTheoThang()
        {
            string apiUrl = $"https://localhost:7016/api/ThongKe/ThongKeDoanhThuTheoThang";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeDoanhThu>>(apiData);

            return View(ChatLieus);
        }
        [HttpGet]
        public async Task<IActionResult> LocThongKeDoanhThuTheoThang(DateTime NgayStart, DateTime NgayEnd)
        {
            string apiUrl = $"https://localhost:7016/api/ThongKe/ThongKeDoanhThuTheoThang";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeDoanhThu>>(apiData);
            var timkiem = ChatLieus.ToList();

            timkiem = timkiem.Where(x => x.Ngay.Month>= NgayStart.Month && x.Ngay.Month <= NgayEnd.Month).ToList();
            return View("ThongKeDoanhThuTheoThang", timkiem);
        }
        [HttpGet]
        public async Task<IActionResult> ThongKeDoanhThuTheoNam()
        {
            string apiUrl = $"https://localhost:7016/api/ThongKe/ThongKeDoanhThuTheoNam";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeDoanhThu>>(apiData);

            return View( ChatLieus);
        }
        [HttpGet]
        public async Task<IActionResult> LocThongKeDoanhThuTheoNam(DateTime NgayStart, DateTime NgayEnd)
        {
            string apiUrl = $"https://localhost:7016/api/ThongKe/ThongKeDoanhThuTheoNam";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeDoanhThu>>(apiData);
            var timkiem = ChatLieus.ToList();

            timkiem = timkiem.Where(x => x.Ngay.Year >= NgayStart.Year && x.Ngay.Year <= NgayEnd.Year).ToList();
            return View("ThongKeDoanhThuTheoNam", timkiem);
        }
        #endregion

    }
}

App_banAo/Views/ThongKe/ThongKeDoanhThuTheoNam.cshtml
@model IEnumerable<App_data.ViewModels.ThongKe.ThongKeDoanhThu>

@{
    ViewData["Title"] = "ThongKeDoanhThuTheoNam";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h2>Thống kê Doanh Thu Theo Năm</h2>

<form method="get" asp-controller="ThongKe" asp-action="LocThongKeDoanhThuTheoNam">
    <label for="thangInput"> Bắt Đầu Từ Năm:</label>
    <input type="datetime-local" id="thangInput" name="NgayStart">
    <label for="thangInput">Kết Thúc Đến Năm: </label>
   <input type="datetime-local" id="thangInput" name="NgayEnd">
    <button type="submit">Thống Kê</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div>
    <canvas id="columnChart" ></canvas>
</div>

<script>
    let labels = [];
    let data = [];

    @foreach (var result in Model)
    {
        <text >labels.push('@result.Ngay.Year-@result.SoHoaDon  ');</text>
        <text>data.push('@result.DoanhThu');</text>
    }

    var ctx = document.getElementById('columnChart').getContext('2d');
    var columnChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Doanh Thu',
                data: data,
                backgroundColor: ' #0d6efd',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 0.5
            }]
        },
        options: {
            scales: {
                x: {
                    title: {
                        display: true,
                        text: 'Năm -Tổng Số Đơn'
                    }
                },
                y: {
                    title: {
                        display: true,
                        text: 'Doanh Thu'
                    },
                    ticks: {
                        beginAtZero: true
                    }
                }
            }
        }
    });
</script>

App_banAo/Views/ThongKe/ThongKeDoanhThuTheoNgay.cshtml
@model IEnumerable<App_data.ViewModels.ThongKe.ThongKeDoanhThu>

@{
    ViewData["Title"] = "ThongKeDoanhThuTheoNgay";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h2>Thống kê Doanh Thu Theo Ngày</h2>

<form method="get" asp-controller="ThongKe" asp-action="LocThongKeDoanhThuTheoNgay">
    <label for="thangInput"> Bắt Đầu Từ Ngày:</label>
    <input type="date" id="thangInput" name="NgayStart">
    <label for="thangInput">Kết Thúc Đến Ngày: </label>
   <input type="date" id="thangInput" name="NgayEnd">
    <button type="submit">Thống Kê</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div>
    <canvas id="columnChart" ></canvas>
</div>

<script>
    let labels = [];
    let data = [];

    @foreach (var result in Model)
    {
        <text>labels.push('@result.Ngay-@result.SoHoaDon ');</text>
        <text>data.push('@result.DoanhThu');</text>
    }

    var ctx = document.getElementById('columnChart').getContext('2d');
    var columnChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Doanh Thu',
                data: data,
                backgroundColor: ' #0d6efd',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 0.5
            }]
        },
        options: {
            scales: {
                x: {
                    title: {
                        display: true,
                        text: 'Ngày -Tổng Số Đơn'
                    }
                },
                y: {
                    title: {
                        display: true,
                        text: 'Doanh Thu'
                    },
                    ticks: {
                        beginAtZero: true
                    }
                }
            }
        }
    });
</script>

App_banAo/Views/ThongKe/ThongKeDoanhThuTheoThang.cshtml
@model IEnumerable<App_data.ViewModels.ThongKe.ThongKeDoanhThu>

@{
    ViewData["Title"] = "ThongKeDoanhThuTheoThang";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h2>Thống kê Doanh Thu Theo Tháng</h2>

<form method="get" asp-controller="ThongKe" asp-action="LocThongKeDoanhThuTheoThang">
    <label for="thangInput"> Bắt Đầu Từ Tháng:</label>
    <input type="Month" id="thangInput" name="NgayStart">
    <label for="thangInput">Kết Thúc Đến Tháng: </label>
   <input type="Month" id="thangInput" name="NgayEnd">
    <button type="submit">Thống Kê</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div>
    <canvas id="columnChart" ></canvas>
</div>

<script>
    let labels = [];
    let data = [];

    @foreach (var result in Model)
    {
        <text>labels.push('@result.Ngay-@result.SoHoaDon ');</text>
        <text>data.push('@result.DoanhThu');</text>
    }

    var ctx = document.getElementById('columnChart').getContext('2d');
    var columnChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Doanh Thu',
                data: data,
                backgroundColor: ' #0d6efd',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 0.5
            }]
        },
        options: {
            scales: {
                x: {
                    title: {
                        display: true,
                        text: 'Tháng - Tổng Số Đơn'
                    }
                },
                y: {
                    title: {
                        display: true,
                        text: 'Doanh Thu'
                    },
                    ticks: {
                        beginAtZero: true
                    }
                }
            }
        }
    });
</script>

App_banAo/Views/ThongKe/ThongKeKH.cshtml
@model App_banAo.Models.PhanTrangThongKeKH

@{
    ViewData["Title"] = "ThongKeKH";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
    int stt = 1;
}

<h1>Thống Kê Khách Hàng</h1>
<form method="get" asp-controller="ThongKe" asp-action="ThongKeSPKHTheoThang">
    <label for="thangInput">Bắt Đầu Từ Tháng:</label>
    <input type="Month" id="thangInput" name="ThangStart">
    <label for="thangInput">Kết Thúc Đến Tháng:</label>
    <input type="month" id="thangInput" name="ThangEnd">

    <button type="submit">Thống Kê</button>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                STT
            </th>

            <th>
                Tên Khách Hàng
            </th>
            <th>
                Số Điện Thoại
            </th>
            <th>
                Email
            </th>
            <th>
                Tổng Số Tiền
            </th>
            <th>
                Số Đơn mua
            </th>
            <th>
                Ngày Thanh Toán
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.listkhs)
        {
            <tr>
                <td>
                    <strong style="color:black">@stt</strong>
                </td>

                <td>
                    <strong style="color:black">@item.Ten</strong>
                </td>
                <td>
                    <strong style="color:black">@item.SDT</strong>
                </td>
                <td>
                    <strong style="color:black">@item.Email</strong>
                </td>
                <td>
                    <strong style="color:red">@item.TongSoTien.ToString("n0") VND</strong>
                </td>
                <td>
                    <strong style="color:green">@item.SoDonMua</strong>
                </td>
                <td>
                    <strong style="color:black">@item.Ngay</strong>
                </td>
                <td>
                    <button class="btn btn-primary">
                        @Html.ActionLink("Chi tiết", "GetAllLSTDByIDKH", new { id = item.idkh }, new { @style = "color:white;" })
                    </button>
                </td>
                @{
                    stt++;
                }
            </tr>
        }
    </tbody>
</table>

<nav>
    <ul class="pagination justify-content-center">
        <li class="page-item disabled"><a class="page-link" href="#">Previous</span></a></li>
        @for (int i = 1; i <= Model.PagingInfo.TotalPages; i++)
        {
            <li class="page-item"><a class="page-link" href="/ThongKe/ThongKeKH?ProductPage=@i">@i</a></li>

        }

        <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
</nav>
</div>

App_banAo/Views/ThongKe/ThongKeSP.cshtml
@model IEnumerable<App_data.ViewModels.ThongKe.ThongKeMSSanPhamTheoSoLuong>

@{
    ViewData["Title"] = "ThongKeSP";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

@*<h2>Thống kê sản phẩm theo số lượng và màu sắc:</h2>

<form method="get" asp-controller="ThongKe" asp-action="ThongKeSPTheoThang">
    <label for="thangInput">Tháng:</label>
    <input type="month" id="thangInput" name="thang">
    <button type="submit">Lọc</button>
</form>

<div id="piechart"></div>

@section Scripts {
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load("current", { packages: ["corechart"] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ["Sản phẩm", "Số lượng"],
        @foreach (var item in Model)
        {
            <text>["@item.TenSP - @item.TenMS", @item.SoLuong], </text>
        }
                ]);

            var options = {
                title: "Thống kê sản phẩm mua theo số lượng và màu sắc",
                is3D: true,
            };

            var chart = new google.visualization.PieChart(document.getElementById("piechart"));
            chart.draw(data, options);
        }
    </script>
}*@
<h2>Thống kê sản phẩm theo số lượng và màu sắc:</h2>

<form method="get" asp-controller="ThongKe" asp-action="ThongKeSPTheoThang">
    <label for="thangInput">Ngày:</label>
    <input type="date" id="thangInput" name="ngay">
    <label for="thangInput">Tháng:</label>
    <input type="month" id="thangInput" name="thang">
    <label for="thangInput">Năm:</label>
    <input type="datetime-local" id="thangInput" name="nam">
    <button type="submit">Lọc</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div>
    <canvas id="columnChart" ></canvas>
</div>

<script>
    let labels = [];
    let data = [];

    @foreach (var result in Model)
    {
        <text>labels.push('@result.TenSP-@result.DoanhThu.ToString("n0") VND ');</text>
        <text>data.push('@result.SoLuong');</text>
    }

    var ctx = document.getElementById('columnChart').getContext('2d');
    var columnChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Số lượng',
                data: data,
                backgroundColor: ' #0d6efd',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 0.5
            }]
        },
        options: {
            scales: {
                x: {
                    title: {
                        display: true,
                        text: 'Tên Sản Phẩm '
                    }
                },
                y: {
                    title: {
                        display: true,
                        text: 'Số lượng'
                    },
                    ticks: {
                        beginAtZero: true
                    }
                }
            }
        }
    });
</script>
@*<!DOCTYPE HTML>
<html>
<head>
    <script>
        window.onload = function () {

            var chart = new CanvasJS.Chart("chartContainer", {
                theme: "light2", // "light1", "light2", "dark1", "dark2"
                exportEnabled: true,
                animationEnabled: true,
                title: {
                    text: "Automotive Semiconductor Vendors 2015",
                    fontSize: 21
                },
                data: [{
                    type: "pie",
                    startAngle: 160,
                    @foreach(var x in ViewBag.ChatLieus){

                    }
                    toolTipContent: "<b>{label}</b>: {y}%",
                    indexLabel: "{label} - {y}%",
                    dataPoints: @Html.Raw(ViewBag.ChatLieus)
            }]
            });
            chart.render();

        }
    </script>
</head>
<body>
    <div id="chartContainer" style="height: 370px; width: 100%;"></div>
    <script src="https://cdn.canvasjs.com/canvasjs.min.js"></script>
    <script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
</body>
</html>*@