App_banAo/Controllers/KhuyenMaiController.cs
using App_banAo.Models;
using App_data.Models;
using App_data.ViewModels;
using App_data.ViewModels.ChiTietSPView;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data;
using System.Drawing.Printing;

namespace App_banAo.Controllers
{
    public class KhuyenMaiController : Controller
    {
        private readonly HttpClient httpClients;

        public KhuyenMaiController()
        {
            httpClients = new HttpClient();
        }
        public IActionResult Index()
        {
            return View();
        }
        public int PageSize = 8;
        [HttpGet]

        public async Task<IActionResult> GetAllKhuyenMai(int ProductPage = 1)
        {   
            //list km
            string apiUrl = "https://localhost:7016/api/KhuyenMai";
            var response = await httpClients.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var KhuyenMais = JsonConvert.DeserializeObject<List<KhuyenMaiView>>(apiData);
            ViewBag.KhuyenMaiView=KhuyenMais;
            
           

                return View(/*CTSanPhams*/

                    new PhanTrangKhuyenMai
                    {
                       listkmv = KhuyenMais
                        .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                        PagingInfo = new PagingInfo
                        {
                            ItemsPerPage = PageSize,
                            CurrentPage = ProductPage,
                            TotalItems = KhuyenMais.Count()
                        }

                    }
                    );
            
            
        }
        [HttpGet]

        public async Task<IActionResult> Search(string Ten,int ProductPage = 1)
        {
            //list km
            string apiUrl = "https://localhost:7016/api/KhuyenMai";
            var response = await httpClients.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var KhuyenMais = JsonConvert.DeserializeObject<List<KhuyenMaiView>>(apiData);
            ViewBag.KhuyenMaiView = KhuyenMais;



            return View("GetAllKhuyenMai",

                new PhanTrangKhuyenMai
                {
                    listkmv = KhuyenMais.Where(x=>x.Ten.Contains(Ten))
                    .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                    PagingInfo = new PagingInfo
                    {
                        ItemsPerPage = PageSize,
                        CurrentPage = ProductPage,
                        TotalItems = KhuyenMais.Count()
                    }

                }
                );


        }
        [HttpGet]

        public async Task<IActionResult> GetAllSPByKM(Guid id,int ProductPage = 1)
        {

            // list anh 
            string urlAnh = "https://localhost:7016/api/Anh";
            var responseAnh = await httpClients.GetAsync(urlAnh);
            string DataAnh = await responseAnh.Content.ReadAsStringAsync();
            var Anh = JsonConvert.DeserializeObject<List<Anh>>(DataAnh);
            ViewBag.Anh = Anh;
            //list km
            string apiUrl = "https://localhost:7016/api/KhuyenMai";
            var response = await httpClients.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var KhuyenMais = JsonConvert.DeserializeObject<List<KhuyenMaiView>>(apiData);
            ViewBag.KhuyenMaiView = KhuyenMais;
            // luu idkhm vo session
            var KhuyenMai = KhuyenMais.FirstOrDefault(x => x.Id == id);

            HttpContext.Session.SetString("IdKhuyenMai", KhuyenMai.Id.ToString());
            // list lsp
            string apiUrllsp = "https://localhost:7016/api/LoaiSP";
            var responselsp = await httpClients.GetAsync(apiUrllsp);
            string apiDatalsp = await responselsp.Content.ReadAsStringAsync();
            var LoaiSPs = JsonConvert.DeserializeObject<List<LoaiSP>>(apiDatalsp);
            ViewBag.LoaiSPs = LoaiSPs;
            // list allspby km
            string apiUrl1 = $"https://localhost:7016/api/KhuyenMai/GetAllSPByKm?id={id}";
            var response1 = await httpClients.GetAsync(apiUrl1);
            string apiData1= await response1.Content.ReadAsStringAsync();
            var KhuyenMais1 = JsonConvert.DeserializeObject<List<AllSanPhamByKM>>(apiData1);


            return View(/*CTSanPhams*/
                
                new PhanTrangSanPhamByKM
                {
                    listsp = KhuyenMais1
                    .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                    PagingInfo = new PagingInfo
                    {
                        ItemsPerPage = PageSize,
                        CurrentPage = ProductPage,
                        TotalItems = KhuyenMais1.Count()
                    }

                }
                );


        }
        [HttpGet]

        public async Task<IActionResult> GetAllSPNoKM( int ProductPage = 1)
        {

            // list anh 
            string urlAnh = "https://localhost:7016/api/Anh";
            var responseAnh = await httpClients.GetAsync(urlAnh);
            string DataAnh = await responseAnh.Content.ReadAsStringAsync();
            var Anh = JsonConvert.DeserializeObject<List<Anh>>(DataAnh);
            ViewBag.Anh = Anh;
            //list km
            string apiUrl = "https://localhost:7016/api/KhuyenMai";
            var response = await httpClients.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var KhuyenMais = JsonConvert.DeserializeObject<List<KhuyenMaiView>>(apiData);
            ViewBag.KhuyenMaiView = KhuyenMais;
            // list lsp
            string apiUrllsp = "https://localhost:7016/api/LoaiSP";
            var responselsp = await httpClients.GetAsync(apiUrllsp);
            string apiDatalsp = await responselsp.Content.ReadAsStringAsync();
            var LoaiSPs = JsonConvert.DeserializeObject<List<LoaiSP>>(apiDatalsp);
            ViewBag.LoaiSPs = LoaiSPs;
            // list allspby km
            // lay idkm tu session
            var idkhuyenmai = Guid.Parse(HttpContext.Session.GetString("IdKhuyenMai"));
            string apiUrl1 = $"https://localhost:7016/api/KhuyenMai/GetAllSPNoKm?id={idkhuyenmai}";
            var response1 = await httpClients.GetAsync(apiUrl1);
            string apiData1 = await response1.Content.ReadAsStringAsync();
            var KhuyenMais1 = JsonConvert.DeserializeObject<List<AllSanPhamByKM>>(apiData1);


            return View(/*CTSanPhams*/

                new PhanTrangSanPhamByKM
                {
                    listsp = KhuyenMais1
                    .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                    PagingInfo = new PagingInfo
                    {
                        ItemsPerPage = PageSize,
                        CurrentPage = ProductPage,
                        TotalItems = KhuyenMais1.Count()
                    }

                }
                );


        }
        [HttpGet]
        public async Task<IActionResult> LocLSPGetAllSPNoKM(Guid id,int ProductPage = 1)
        {

            // list anh 
            string urlAnh = "https://localhost:7016/api/Anh";
            var responseAnh = await httpClients.GetAsync(urlAnh);
            string DataAnh = await responseAnh.Content.ReadAsStringAsync();
            var Anh = JsonConvert.DeserializeObject<List<Anh>>(DataAnh);
            ViewBag.Anh = Anh;
            //list km
            string apiUrl = "https://localhost:7016/api/KhuyenMai";
            var response = await httpClients.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var KhuyenMais = JsonConvert.DeserializeObject<List<KhuyenMaiView>>(apiData);
            ViewBag.KhuyenMaiView = KhuyenMais;
            // list lsp
            string apiUrllsp = "https://localhost:7016/api/LoaiSP";
            var responselsp = await httpClients.GetAsync(apiUrllsp);
            string apiDatalsp = await responselsp.Content.ReadAsStringAsync();
            var LoaiSPs = JsonConvert.DeserializeObject<List<LoaiSP>>(apiDatalsp);
            ViewBag.LoaiSPs = LoaiSPs;
            // list allspby km
            // lay idkm tu session
            var idkhuyenmai = Guid.Parse(HttpContext.Session.GetString("IdKhuyenMai"));
            string apiUrl1 = $"https://localhost:7016/api/KhuyenMai/GetAllSPNoKm?id={idkhuyenmai}";
            var response1 = await httpClients.GetAsync(apiUrl1);
            string apiData1 = await response1.Content.ReadAsStringAsync();
            var KhuyenMais1 = JsonConvert.DeserializeObject<List<AllSanPhamByKM>>(apiData1);
            

            return View(/*CTSanPhams*/

                new PhanTrangSanPhamByKM
                {
                    listsp = KhuyenMais1.Where(x=>x.IdLoaiSP==id)
                    .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                    PagingInfo = new PagingInfo
                    {
                        ItemsPerPage = PageSize,
                        CurrentPage = ProductPage,
                        TotalItems = KhuyenMais1.Count()
                    }

                }
                );


        }
        [HttpGet]
        public async Task<IActionResult> AddKHuyenMaiVoSP(Guid id,int ProductPage = 1)
        {

            // list anh 
            string urlAnh = "https://localhost:7016/api/Anh";
            var responseAnh = await httpClients.GetAsync(urlAnh);
            string DataAnh = await responseAnh.Content.ReadAsStringAsync();
            var Anh = JsonConvert.DeserializeObject<List<Anh>>(DataAnh);
            ViewBag.Anh = Anh;
            //list km
            string apiUrl = "https://localhost:7016/api/KhuyenMai";
            var response = await httpClients.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();

App_banAo/Views/KhuyenMai/AddKHuyenMaiVoSP.cshtml
@using App_data.Models
@using App_data.ViewModels.ChiTietSPView
@model App_banAo.Models.ProductListViewModel
@{
    ViewData["Title"] = "AddKHuyenMaiVoSP";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
    List<KhuyenMaiView> listkms = ViewBag.KhuyenMaiView;
    List<ChiTietSanPham> listctsp = ViewBag.ChiTietSanPham;
    List<SanPham> listsp = ViewBag.SanPham;
    List<MauSac> listms = ViewBag.MauSac;
    List<Size> listsize = ViewBag.Size;
    List<Anh> listanh = ViewBag.Anh;
    int stt = 1;

    List<string> imageExtensions = new List<string>()
    {
         ".png", ".jpg", ".jpeg", ".gif", ".tiff", ".pdf",".webp",".jfif"
    };

}

   


<h2>Các Chi Tiết Sản Phẩm</h2>
<hr />

            
                

            
            <!-- Nhieu CSTP start-->

<table class="table">
    <thead>
        <tr>
            <th>
                Chọn
            </th>
            <th>
                STT
            </th>

            <th>
                Tên SP
            </th>
            <th>
                Ảnh
            </th>

            <th>
                Tên Khuyến Mãi
            </th>
            <th>
                Tên Màu Sắc
            </th>
            <th>
                Tên Size
            </th>
            <th>
                Giá Khuyến Mãi
            </th>
            <th>
                Giá Trị KM
            </th>
            <th>
                Giá Gốc
            </th>
            <th>
                Trạng Thái
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.chiTietSanPhams)
        {
            <tr>
                <td>
                    <input type="checkbox" class="sanpham-checkbox" data-id="@item.Id">
                </td>
                <td>
                    @stt
                </td>

                <td>
                    <strong style="color:red">@item.TenSanPham</strong>
                </td>
                <td>
                    @{

                        if (item.TenAnh != null)
                        {
                            string extension = System.IO.Path.GetExtension(item.TenAnh);
                            if (imageExtensions.Contains(extension.Trim()))
                            {
                                <img class="img-fluid w-100" src="~/userassets/img/@item.TenAnh" />
                            }
                            else
                            {
                                <img class="img-fluid w-100" src="~/imgs/product-2.jpg" height="100px">
                            }
                        }
                        else
                        {
                            <strong></strong>
                        }
                    }
                </td>

                <td>
                    @{
                        var idCt = listctsp.FirstOrDefault(x => x.Id == item.Id);
                        var tk = listkms.FirstOrDefault(x => x.Id == idCt.IdKhuyenMai);
                        if (tk != null)
                        {
                            if (tk.NgayKetThuc >= DateTime.Now)
                            {
                                <strong style="color:green">@tk.Ten</strong>
                            }
                            else if (tk.NgayKetThuc < DateTime.Now)
                            {
                                <strong style="color:red">@tk.Ten hết hạn rồi</strong>
                            }

                        }
                        else
                        {
                            <strong></strong>
                        }
                    }
                </td>

                <td>
                    <strong style="color:brown">@item.TenMauSac</strong>
                </td>
                <td>
                    <strong style="color:red">@item.TenSize</strong>
                </td>
                <td>
                    @{
                        if (tk != null)
                        {
                            if (tk.NgayKetThuc >= DateTime.Now)
                            {
                                <strong style="color:green">$@(item.GiaKhuyenMai - item.GiaKhuyenMai * tk.GiaTri / 100) VND</strong>
                            }
                            else if (tk.NgayKetThuc < DateTime.Now)
                            {
                                <strong style="color:red">$@item.GiaGoc.ToString("n0") VND</strong>
                            }
                        }
                        else
                        {
                            <strong style="color:red">$@item.GiaGoc.ToString("n0") VND</strong>
                        }
                    }

                </td>
                <td>
                    @{
                        if (tk != null)
                        {
                            <strong style="color:green">@tk.GiaTri%</strong>
                        }
                        else
                        {
                            <strong></strong>
                        }
                    }

                </td>
                <td>
                    <strong style="color:red"><del>$@item.GiaGoc.ToString("n0") VND</del></strong>
                </td>
                <td>
                    @{

                        if (item.TrangThai == 0)
                        {
                            <strong style="color:red">Hết Hàng</strong>
                        }
                        else
                        {
                            <strong style="color:green">Còn Hàng</strong>
                        }
                    }

                </td>
                 @{
                    stt++;
                }
            </tr>
        }
    </tbody>
</table>
<div class="col-12">
    <nav>
        <ul class="pagination justify-content-center">
            <li class="page-item disabled"><a class="page-link" href="#">Previous</span></a></li>
            @for (int i = 1; i <= Model.PagingInfo.TotalPages; i++)
            {
                <li class="page-item"><a class="page-link" href="/KhuyenMai/AddKHuyenMaiVoSP?ProductPage=@i">@i</a></li>

            }

            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>
</div>
          
            <!-- Nhieu CSTP end-->
<button id="selectAllCheckbox" class="btn btn-primary">Chọn tất cả</button>
<br />
<div class="form-group">
    <button id="updateButton" class="btn btn-primary">Áp Dụng Khuyến Mãi</button>
    <button id="DeleteButton" class="btn btn-danger">Không Áp Dụng Khuyến Mãi</button>
</div>
   

<div>
    <a asp-action="GetAllKhuyenMai">Quay lại</a>
</div>
<!-- JavaScript Libraries -->
<script src="~/js/jquery-3.3.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

<script>
    $(document).ready(function () {
        // Sự kiện khi click vào "Chọn tất cả"
        $("#selectAllCheckbox").click(function () {
            $(".sanpham-checkbox").prop("checked", true);
        });

        // Sự kiện khi click vào "Cập nhật"
        $("#updateButton").click(function () {
            
            var selectedSanPham = [];

            $(".sanpham-checkbox:checked").each(function () {
                selectedSanPham.push($(this).data("id"));
            });

            // Gửi dữ liệu lên server để cập nhật
            $.ajax({
                url: "/KhuyenMai/AddKHuyenMaiVoSP",
                type: "POST",
                data: {
                    
                    sanphams: selectedSanPham
                },
                success: function (response) {
                    if (response.success == true) {
                            location.reload();
                    } else {
                        toastr.error(response.message, 'Error Alert', { timeOut: 300 });
                    }
                },
                error: function (response) {
                    console.log(response);
                    toastr.error(response.message, 'Error Alert', { timeOut: 300 });
                }
            });
                
        });
            $("#DeleteButton").click(function () {

                var selectedSanPham = [];

                $(".sanpham-checkbox:checked").each(function () {
                    selectedSanPham.push($(this).data("id"));
                });

                // Gửi dữ liệu lên server để cập nhật
                $.ajax({
                    url: "/KhuyenMai/DeleteKHuyenMaiRaSP",
                    type: "POST",
                    data: {

                        sanphams: selectedSanPham
                    },
                    success: function (response) {
                        if (response.success == true) {
                            location.reload();
                        } else {
                            toastr.error(response.message, 'Error Alert', { timeOut: 300 });
                        }
                    },
                    error: function (response) {
                        console.log(response);
                        toastr.error(response.message, 'Error Alert', { timeOut: 300 });
                    }
                });

            });
    });

</script>

App_banAo/Views/KhuyenMai/Create.cshtml
@model App_data.ViewModels.ChiTietSPView.KhuyenMaiView

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h2>Create</h2>

<h4>KhuyenMai</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ten" class="control-label">Tên</label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaTri" class="control-label">Giá Trị</label>
                <input asp-for="GiaTri" class="form-control" />
                <span asp-validation-for="GiaTri" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayApDung" class="control-label">Ngày Áp Dụng</label>
                <input asp-for="NgayApDung" class="form-control" />
                <span asp-validation-for="NgayApDung" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayKetThuc" class="control-label">Ngày Kết Thúc</label>
                <input asp-for="NgayKetThuc" class="form-control" />
                <span asp-validation-for="NgayKetThuc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoTa" class="control-label">Mô Tả</label>
                <input asp-for="MoTa" class="form-control" />
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrangThai" class="control-label">
                    Trạng Thái
                </label>
                <input asp-for="TrangThai" class="form-control" />
                <span asp-validation-for="TrangThai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

App_banAo/Views/KhuyenMai/Details.cshtml
@model App_data.Models.KhuyenMai

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h2>Chi Tiết</h2>

<div>
    <h4>Khuyến Mại</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt>
            Giá Trị
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GiaTri)
        </dd>
        <dt>
            Ngày Áp Dụng
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NgayApDung)
        </dd>
        <dt>
            Ngày Kết Thúc
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NgayKetThuc)
        </dd>
        <dt>
            Mô Tả
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>
        <dt>
            Trạng Thái
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

App_banAo/Views/KhuyenMai/GetAllKhuyenMai.cshtml
@using App_data.Models

@model App_banAo.Models.PhanTrangKhuyenMai

@{
    ViewData["Title"] = "GetAllKhuyenMai";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml"; int stt = 1;
}
<h2>Quản Lý Khuyến Mại</h2>

<p>
    <a asp-action="Create">Thêm Mới Khuyến mãi</a>
</p>
<form asp-action="Search" asp-area="Admin" asp-controller="KhuyenMai" method="get" enctype="multipart/form-data" style="width:50%">
    <button type="submit" class="fa fa-search"></button>
    <div class="input-group">
        <input type="text" name="Ten" class="form-control" placeholder="Tìm Theo Mã Khuyến Mãi">
    </div>

</form>
<table class="table">
    <thead>
        <tr>
            <th>
                STT
            </th>

            <th>
                Tên
            </th>
            <th>
                Giá Trị
            </th>
            <th>
                Ngày Áp Dụng
            </th>
            <th>
                Ngày Kết Thúc
            </th>
            <th>
                Mô Tả
            </th>
            <th>
                Trạng Thái
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.listkmv) {
            <tr>
                <td>
                    <strong style="color:black">@stt</strong>
                </td>

            <td>
                    <strong style="color:red">@item.Ten</strong>
            </td>
            <td>
                    <strong style="color:green">@item.GiaTri%</strong>
            </td>
            <td>
                    <strong style="color:green">@item.NgayApDung</strong>
            </td>
            <td>
            @if(item.NgayKetThuc>=DateTime.Now){
                        <strong style="color:green">@item.NgayKetThuc</strong>
            }
            else{
                        <strong style="color:red">@item.NgayKetThuc</strong>
            }
                   
            </td>
            <td>
                    <strong style="color:black">@item.MoTa</strong>
            </td>
            <td>
                    @{
                        if(item.NgayKetThuc>=DateTime.Now){
                            <strong style="color:green">còn khuyến mãi</strong>
                        }
                        else{
                            <strong style="color:red">Hết Khuyến mãi</strong>
                        }
                    }

            </td>
            <td>
                    <button class="btn btn-success">
                        @Html.ActionLink("Sửa", "Update", new { id = item.Id }, new { @style = "color:white;" })
                    </button>
                    <button class="btn btn-primary">
                        @Html.ActionLink("Chi tiết", "GetAllSPByKM", new { id = item.Id }, new { @style = "color:white;" })
                    </button>
                    <button class="btn btn-danger">
                        @Html.ActionLink("Xóa", "Delete", new { id = item.Id }, new { @style = "color:white;" })
                    </button>
                </td> @{
                    stt++;
                }
        </tr>
}
    </tbody>
</table>
<div class="col-12">
    <nav>
        <ul class="pagination justify-content-center">
            <li class="page-item disabled"><a class="page-link" href="#">Previous</span></a></li>
            @for (int i = 1; i <= Model.PagingInfo.TotalPages; i++)
            {
                <li class="page-item"><a class="page-link" href="/KhuyenMai/GetAllKhuyenMai?ProductPage=@i">@i</a></li>

            }

            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>
</div>

App_banAo/Views/KhuyenMai/GetAllSPNoKM.cshtml
@using App_data.Models
@model App_banAo.Models.PhanTrangSanPhamByKM

@{
    ViewData["Title"] = "GetAllSPNoKM";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
    int stt = 1;
    List<Anh> listanh = ViewBag.Anh;
    List<LoaiSP> listlsp = ViewBag.LoaiSPs;
    List<string> imageExtensions = new List<string>()
    {
         ".png", ".jpg", ".jpeg", ".gif", ".tiff", ".pdf",".webp",".jfif"
    };
}
<form asp-controller="KhuyenMai" asp-action="LocLSPGetAllSPNoKM" method="get" enctype="multipart/form-data">
    <div>

        <select name="id" class="form-control" style="width:600px;height:40px">
            if (idloaisp == null)
            {
            <option value="">Chọn Tên Loại SP</option>
            }
            @foreach (var loaisp in listlsp.ToList())
            {
                <option value="@loaisp.Id">@loaisp.Ten</option>
            }

        </select>

        
    </div>

    <button type="submit" class="fa fa-search"></button>


</form>
<table class="table">
    <thead>
        <tr>
            <th>
                STT
            </th>
            <th>
                Tên Sản Phẩm
            </th>
            <th>
                Ảnh
            </th>
            <th>
                Số Lượng Chi Tiết
            </th>

            <th>
                Tên Loại SP
            </th>
            <th>
                Tên Loại SP Cha
            </th>
            <th>
                Mo Tả
            </th>
            <th>
                Trạng Thái
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.listsp)
        {
            <tr>
                <td>
                    <strong style="color:black">@stt</strong>
                </td>
                <td>
                    <strong style="color:black">@item.Ten</strong>
                </td>
                <td>
                    @{

                        if (item.TenAnh != null)
                        {
                            string extension = System.IO.Path.GetExtension(item.TenAnh);
                            if (imageExtensions.Contains(extension.Trim()))
                            {
                                <img class="img-fluid w-100" src="~/userassets/img/@item.TenAnh" />
                            }
                            else
                            {
                                <img class="img-fluid w-100" src="~/imgs/product-2.jpg" height="100px">
                            }
                        }
                        else
                        {
                            <strong></strong>
                        }
                    }
                </td>
                <td>
                    <strong style="color:green">@item.SLCTSP</strong>
                </td>

                <td>
                    @{
                        var loaisp = listlsp.FirstOrDefault(x => x.Id == item.IdLoaiSP);
                        if (loaisp != null)
                        {
                            <strong style="color:black">@loaisp.Ten</strong>
                        }
                    }
                </td>
                <td>
                    @{
                        var loaisps = listlsp.FirstOrDefault(x => x.Id == item.IdLoaiSpCha);
                        if (loaisps != null)
                        {
                            <strong style="color:black">@loaisps.Ten</strong>
                        }
                    }
                </td>
                <td>
                    <strong style="color:black">@item.MoTa</strong>
                </td>
                <td>
                    @{
                        if (item.TrangThai == 0)
                        {
                            <strong style="color:red">Hết </strong>
                        }
                        else
                        {
                            <strong style="color:green">Còn </strong>
                        }
                    }
                </td>
                <td>
                    <button class="btn btn-success">
                        @Html.ActionLink("Chi Tiết", "AddKHuyenMaiVoSP", new { id = item.Id }, new { @style = "color:white;" })
                    </button>
                </td>
                @{
                    stt++;
                }
            </tr>
        }
    </tbody>
</table>
<div class="col-12">
    <nav>
        <ul class="pagination justify-content-center">
            <li class="page-item disabled"><a class="page-link" href="#">Previous</span></a></li>
            @for (int i = 1; i <= Model.PagingInfo.TotalPages; i++)
            {
                <li class="page-item"><a class="page-link" href="/KhuyenMai/GetAllSPNoKM?ProductPage=@i">@i</a></li>

            }

            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>
</div>