App_banAo/Controllers/AnhController.cs
using App_banAo.Models;
using App_data.Models;
using Microsoft.AspNetCore.Http.Metadata;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Drawing.Printing;

namespace App_banAo.Controllers
{
    public class AnhController : Controller
    {
        
      
        private readonly HttpClient httpClients;
        public int PageSize = 9;


        public AnhController()
        {
            httpClients = new HttpClient();
           
        }


        [HttpGet]

        public async Task<IActionResult> GetAllAnh(int ProductPage = 1)
        {
           
            string apiUrl = "https://localhost:7016/api/Anh";
            var response = await httpClients.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var Anhs = JsonConvert.DeserializeObject<List<Anh>>(apiData);
            return View(new AnhViewModel
            {
                Anhs = Anhs
        .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    ItemsPerPage = PageSize,
                    CurrentPage = ProductPage,
                    TotalItems = Anhs.Count()
                }
            });

            //return View(Anhs);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Create([Bind]IFormFile formFile, Anh anh)
        {
            if (formFile != null && formFile.Length > 0) // Kiểm tra đường dẫn phù hợp
            {
                //check ảnh tồn tại trong folder chưa
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot","userassets",
                    "img", formFile.FileName);
                if (!System.IO.File.Exists(path))
                {
                    // thực hiện việc sao chép ảnh đó vào wwwroot
                    // Tạo đường dẫn tới thư mục sao chép (nằm trong root)
                    // abc/wwwroot/images/xxx.
                    var stream = new FileStream(path, FileMode.Create); // Tạo 1 filestream để tạo mới
                    formFile.CopyTo(stream); // Copy ảnh vừa dc chọn vào đúng cái stream đó

                    // Gán lại giá trị link ảnh (lúc này đã nằm trong root cho thuộc tính description)
                    anh.Ten = formFile.FileName;
                }
                else
                {
                    anh.Ten = formFile.FileName;
                }

            }
            var url = $"https://localhost:7016/api/Anh?Ten={anh.Ten}&TrangThai={anh.TrangThai}";
            var response = await httpClients.PostAsync(url, null);
            if (response.IsSuccessStatusCode) return RedirectToAction("GetAllAnh");
            return View();
        }
        [HttpGet]

        public async Task<IActionResult> Details(Guid id)
        {

            string apiUrl = "https://localhost:7016/api/Anh/" + id;
            var response = await httpClients.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var Anhs = JsonConvert.DeserializeObject<Anh>(apiData);
            return View(Anhs);

        }

        public IActionResult Update(Guid id)
        {
            var url = $"https://localhost:7016/api/Anh/{id}";
            var response = httpClients.GetAsync(url).Result;
            var result = response.Content.ReadAsStringAsync().Result;
            var Anhs = JsonConvert.DeserializeObject<Anh>(result);
            return View(Anhs);
        }
        [HttpPost]

        public async Task<IActionResult> Update(Anh anh,[Bind]IFormFile formFile)
        {
            if (formFile != null && formFile.Length > 0) // Kiểm tra đường dẫn phù hợp
            {
                //check ảnh tồn tại trong folder chưa
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "userassets",
                    "img", formFile.FileName);
                if (!System.IO.File.Exists(path))
                {
                    // thực hiện việc sao chép ảnh đó vào wwwroot
                    // Tạo đường dẫn tới thư mục sao chép (nằm trong root)
                    // abc/wwwroot/images/xxx.
                    var stream = new FileStream(path, FileMode.Create); // Tạo 1 filestream để tạo mới
                    formFile.CopyTo(stream); // Copy ảnh vừa dc chọn vào đúng cái stream đó

                    // Gán lại giá trị link ảnh (lúc này đã nằm trong root cho thuộc tính description)
                    anh.Ten = formFile.FileName;
                }
                else
                {
                    anh.Ten = formFile.FileName;
                }

            }
            var url =
                $"https://localhost:7016/api/Anh/{anh.Id}?Ten={anh.Ten}&TrangThai={anh.TrangThai}";
            var response = await httpClients.PutAsync(url, null);
            if (response.IsSuccessStatusCode) return RedirectToAction("GetAllAnh");
            return View();
        }


        public async Task<IActionResult> Deletes(Guid id)
        {
            var url = $"https://localhost:7016/api/Anh/{id}";
            var response = await httpClients.DeleteAsync(url);
            if (response.IsSuccessStatusCode) return RedirectToAction("GetAllAnh");
            return BadRequest();
        }
    }
}

App_banAo/Controllers/SizeController.cs
using App_banAo.Models;
using App_data.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace App_banAo.Controllers
{
    public class SizeController : Controller
    {
         private readonly HttpClient httpClients;
        public int PageSize = 9;

        public SizeController()
        {
            httpClients = new HttpClient();
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetAllSize(int ProductPage = 1)
        {
            string apiUrl = "https://localhost:7016/api/Size";
            var response = await httpClients.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var Sizes = JsonConvert.DeserializeObject<List<Size>>(apiData);
            return View(new SizeViewmodel
            {
                sizes = Sizes
         .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    ItemsPerPage = PageSize,
                    CurrentPage = ProductPage,
                    TotalItems = Sizes.Count()
                }
            });
            //return View(Sizes);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Create(Size size)
        {
            var url = $"https://localhost:7016/api/Size?Ten={size.Ten}&TrangThai={size.TrangThai}";
            var response = await httpClients.PostAsync(url, null);
            if (response.IsSuccessStatusCode) return RedirectToAction("GetAllSize");
            return View();
        }
        [HttpGet]

        public async Task<IActionResult> Details(Guid id)
        {

            string apiUrl = "https://localhost:7016/api/Size/" + id;
            var response = await httpClients.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var Sizes = JsonConvert.DeserializeObject<Size>(apiData);
            return View(Sizes);

        }

        public IActionResult Update(Guid id)
        {
            var url = $"https://localhost:7016/api/Size/{id}";
            var response = httpClients.GetAsync(url).Result;
            var result = response.Content.ReadAsStringAsync().Result;
            var Sizes = JsonConvert.DeserializeObject<Size>(result);
            return View(Sizes);
        }
        [HttpPost]

        public async Task<IActionResult> Update(Size size)
        {

            var url = $"https://localhost:7016/api/Size/{size.Id}?Ten={size.Ten}&TrangThai={size.TrangThai}";
            var response = await httpClients.PutAsync(url, null);
            if (response.IsSuccessStatusCode) return RedirectToAction("GetAllSize");


            return View();
        }


        public async Task<IActionResult> Delete(Guid id)
        {
            var url = $"https://localhost:7016/api/Size/{id}";
            var response = await httpClients.DeleteAsync(url);
            if (response.IsSuccessStatusCode) return RedirectToAction("GetAllSize");
            return BadRequest();
        }
    }
}

App_banAo/Areas/Admin/Views/Shared/Admin_Layout.cshtml
@{
    var username = Context.Session.GetString("Email");
}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Responsive Bootstrap Advance Admin Template</title>

    <!-- BOOTSTRAP STYLES-->
    <link href="~/Adminassets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="~/Adminassets/css/font-awesome.css" rel="stylesheet" />
    <!--CUSTOM BASIC STYLES-->
    <link href="~/Adminassets/css/basic.css" rel="stylesheet" />
    <!--CUSTOM MAIN STYLES-->
    <link href="~/Adminassets/css/custom.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->

</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">COMPANY NAME</a>
            </div>

            <div class="header-right">

                <a href="message-task.html" class="btn btn-info" title="New Message"><b>30 </b><i class="fa fa-envelope-o fa-2x"></i></a>
                <a href="message-task.html" class="btn btn-primary" title="New Task"><b>40 </b><i class="fa fa-bars fa-2x"></i></a>
                @username
                <li><a class="dropdown-item" asp-controller="TaiKhoan" asp-action="LogOut">Logout</a></li>
                

            </div>
        </nav>
        <!-- /. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li>
                        <div class="user-img-div">
                            <img src="~/Adminassets/img/user.png" class="img-thumbnail" />

                            <div class="inner-text">
                                Jhon Deo Alex
                                <br />
                                <small>Last Login : 2 Weeks Ago </small>
                            </div>
                        </div>

                    </li>


                    
                    <li>
                        <a asp-area ="Admin" asp-controller="ThanhToan" asp-action="GetAllHoaDon"><i class="fa fa-desktop "></i>Quản lý đơn hàng  <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="panel-tabs.html"><i class="fa fa-toggle-on"></i>Tabs & Panels</a>
                            </li>



                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-yelp "></i>Extra Pages <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="active-menu" asp-controller="ThongKe" asp-action="ThongKeSP"><i class="fa fa-dashboard ">Thống Kê Sản Phẩm</i></a>
                            </li>
                            <li>
                                <a class="active-menu" asp-controller="ThongKe" asp-action="ThongKeKH"><i class="fa fa-dashboard ">Thống Kê Khách Hàng </i></a>
                            </li>
                            <li>
                                <a class="active-menu" asp-controller="ThongKe" asp-action="ThongKeDoanhThuTheoNgay"><i class="fa fa-dashboard ">Doanh Thu Theo Ngày </i></a>
                            </li>
                            <li>
                                <a class="active-menu" asp-controller="ThongKe" asp-action="ThongKeDoanhThuTheoThang"><i class="fa fa-dashboard ">Doanh Thu Theo Tháng </i></a>
                            </li>
                            <li>
                                <a class="active-menu" asp-controller="ThongKe" asp-action="ThongKeDoanhThuTheoNam"><i class="fa fa-dashboard ">Doanh Thu Theo Năm </i></a>
                            </li>

                        </ul>
                    </li>
                    <li>
                        <a asp-area="Admin"  asp-controller="SanPham" asp-action="GetAllSanPham"><i class="fa fa-flash "></i>San pham </a>

                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="KhuyenMai" asp-action="GetAllKhuyenMai"><i class="fa fa-flash "></i>Khuyến Mại</a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="ChiTietSP" asp-action="GetAllChiTietSanPhamAdmin"><i class="fa fa-flash "></i>Chi Tiet SP </a>

                    </li>


                    <li>
                        <a href="#"><i class="fa fa-bicycle "></i>Forms <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">

                            <li>
                                <a asp-area="Admin" asp-controller="Anh" asp-action="GetAllAnh"><i class="fa fa-coffee"></i>Ảnh</a>
                            </li>
                            <li>
                                <a asp-area="Admin" asp-controller="MauSac" asp-action="GetAllMauSac"><i class="fa fa-coffee"></i>Màu Sắc</a>
                            </li>
                            <li>
                                <a asp-area="Admin" asp-controller="ChatLieu" asp-action="GetAllChatLieu"><i class="fa fa-flash "></i>Chất Liệu</a>
                            </li>
                            
                            <li>
                                <a asp-area="Admin" asp-controller="LoaiSP" asp-action="GetAllLoaiSP"><i class="fa fa-flash "></i>Loại Sản Phẩm</a>
                            </li>
                            <li>
                                <a asp-area="Admin" asp-controller="Size" asp-action="GetAllSize"><i class="fa fa-flash "></i>Size </a>
                            </li>
                            <li>
                                <a asp-area="Admin" asp-controller="NhaCungCap" asp-action="GetAllNhaCungCap"><i class="fa fa-flash "></i>Nhà Cung Cấp</a>
                            </li>
                           


                        </ul>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="TaiKhoan" asp-action="UpdateTTAdmin"><i class="fa fa-flash "></i>Thông Tin Của Tôi</a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="TaiKhoan" asp-action="GetAllTKKH"><i class="fa fa-flash "></i>Thông Tin Khách Hàng</a>
                    </li>


                    <li>
                        <a href="blank.html"><i class="fa fa-square-o "></i>Blank Page</a>
                    </li>
                </ul>

            </div>

        </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">
                @RenderBody()

            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->

    <div id="footer-sec">
        &copy; 2014 YourCompany | Design By : <a href="http://www.binarytheme.com/" target="_blank">BinaryTheme.com</a>
    </div>
    <!-- /. FOOTER  -->
    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <!-- BOOTSTRAP SCRIPTS -->
    <!-- METISMENU SCRIPTS -->
   
    @await RenderSectionAsync("Scripts",required:false)


</body>
</html>